# Control file:

This script aims at controling for the number of points that are geolocated for each city and discover where are the weaknesses in that process.

In [1]:
# llibreries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
# mount google colab
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [3]:
%cd /content/drive/MyDrive/2_FEINA/10_HU/01_TASKS/01_DIRECTORIES

/content/drive/MyDrive/2_FEINA/10_HU/01_TASKS/01_DIRECTORIES

In [4]:
cities = pd.read_excel('City_list_coreUS.xlsx')
cities.head()

,Unnamed: 0,metro_id,country,metro,Siglas,Downloaded,Cropped,Pre-Processed,Post-Processed,Geo-refferenced,AI OCR,Unnamed: 11,Unnamed: 12
0,1,5,USA,Atlanta,GA,Yes,Yes,Yes,Yes,Yes,Yes,NaN,NaN
1,2,6,USA,Austin,TX,Yes,Yes,Yes,Yes,Yes,Yes,NaN,NaN
2,3,13,USA,Boston,MA,Yes,Yes,Yes,Yes,Yes,Yes,NaN,NaN
3,4,21,USA,Charlotte,NC,Yes,Yes,Yes,Yes,Yes,Yes,NaN,NaN
4,5,23,USA,Chicago,IL,Yes,Yes,Yes,Yes,Yes,Yes,NaN,NaN

In [5]:
# create a list with all cities:
city_list = []
for element in cities['metro']:
  city_list.append(element)

print(city_list)

['Atlanta', 'Austin', 'Boston', 'Charlotte', 'Chicago', 'Cincinnati', 'Cleveland', 'Columbus', 'Dallas', 'Denver', 'Detroit', 'Fort Lauderdale', 'Fort Worth', 'Houston', 'Indianapolis', 'Kansas City', 'Las Vegas', 'Lexington', 'Los Angeles', 'Miami', 'Milwaukee', 'Minneapolis', 'Nashville', 'New York', 'Newark', 'Orlando', 'Philadelphia', 'Phoenix', 'Pittsburgh', 'Portland', 'Providence', 'Riverside', 'Sacramento', 'Saint Louis', 'San Antonio', 'San Diego', 'San Francisco', 'San Jose', 'Seattle', 'Tampa', 'Virginia Beach', 'Washington']

## Geolocation Comparison:

I compare the total geolocated points in both models used. Tesseract and AI OCR using gemini.

### Tesseract

In [6]:
# Iteració:
ratios={}
for element in city_list:
  file_path = f'geo_files/{element}/geo_{element}.csv'
  if os.path.exists(file_path):
    geo_city = pd.read_csv(f'geo_files/{element}/geo_{element}.csv')

    # Sum all full addresses which are not na
    geo_addresscount = geo_city['Full_Address'].notna().sum()
    geo_located = geo_city['Latitude'].count()
    print(f"City: {element}, Number of addresses: {geo_addresscount}, Number of georeferenced points: {geo_located}, ratio: {geo_located/geo_addresscount}")
    ratios.update({element:geo_located/geo_addresscount})
  else:
    print(f"City: {element} not found")
    continue

City: Atlanta, Number of addresses: 118, Number of georeferenced points: 28, ratio: 0.23728813559322035
City: Austin, Number of addresses: 37, Number of georeferenced points: 13, ratio: 0.35135135135135137
City: Boston, Number of addresses: 641, Number of georeferenced points: 275, ratio: 0.4290171606864275
City: Charlotte, Number of addresses: 23, Number of georeferenced points: 9, ratio: 0.391304347826087
City: Chicago, Number of addresses: 1743, Number of georeferenced points: 927, ratio: 0.53184165232358
City: Cincinnati, Number of addresses: 130, Number of georeferenced points: 20, ratio: 0.15384615384615385
City: Cleveland, Number of addresses: 224, Number of georeferenced points: 28, ratio: 0.125
City: Columbus, Number of addresses: 66, Number of georeferenced points: 15, ratio: 0.22727272727272727
City: Dallas, Number of addresses: 160, Number of georeferenced points: 15, ratio: 0.09375
City: Denver, Number of addresses: 160, Number of georeferenced points: 5, ratio: 0.03125
City: Detroit, Number of addresses: 45, Number of georeferenced points: 4, ratio: 0.08888888888888889
City: Fort Lauderdale not found
City: Fort Worth, Number of addresses: 96, Number of georeferenced points: 13, ratio: 0.13541666666666666
City: Houston, Number of addresses: 152, Number of georeferenced points: 16, ratio: 0.10526315789473684
City: Indianapolis, Number of addresses: 200, Number of georeferenced points: 20, ratio: 0.1
City: Kansas City, Number of addresses: 735, Number of georeferenced points: 61, ratio: 0.08299319727891157
City: Las Vegas not found
City: Lexington, Number of addresses: 15, Number of georeferenced points: 7, ratio: 0.4666666666666667
City: Los Angeles, Number of addresses: 744, Number of georeferenced points: 124, ratio: 0.16666666666666666
City: Miami not found
City: Milwaukee, Number of addresses: 218, Number of georeferenced points: 63, ratio: 0.2889908256880734
City: Minneapolis, Number of addresses: 382, Number of georeferenced points: 29, ratio: 0.07591623036649214
City: Nashville, Number of addresses: 94, Number of georeferenced points: 48, ratio: 0.5106382978723404
City: New York, Number of addresses: 3555, Number of georeferenced points: 2596, ratio: 0.730239099859353
City: Newark, Number of addresses: 229, Number of georeferenced points: 125, ratio: 0.5458515283842795
City: Orlando not found
City: Philadelphia, Number of addresses: 1522, Number of georeferenced points: 551, ratio: 0.3620236530880421
City: Phoenix, Number of addresses: 33, Number of georeferenced points: 11, ratio: 0.3333333333333333
City: Pittsburgh, Number of addresses: 399, Number of georeferenced points: 125, ratio: 0.3132832080200501
City: Portland, Number of addresses: 677, Number of georeferenced points: 241, ratio: 0.3559822747415066
City: Providence, Number of addresses: 139, Number of georeferenced points: 79, ratio: 0.5683453237410072
City: Riverside not found
City: Sacramento, Number of addresses: 79, Number of georeferenced points: 34, ratio: 0.43037974683544306
City: Saint Louis, Number of addresses: 380, Number of georeferenced points: 204, ratio: 0.5368421052631579
City: San Antonio, Number of addresses: 107, Number of georeferenced points: 23, ratio: 0.21495327102803738
City: San Diego, Number of addresses: 96, Number of georeferenced points: 12, ratio: 0.125
City: San Francisco, Number of addresses: 428, Number of georeferenced points: 91, ratio: 0.21261682242990654
City: San Jose, Number of addresses: 36, Number of georeferenced points: 4, ratio: 0.1111111111111111
City: Seattle, Number of addresses: 532, Number of georeferenced points: 196, ratio: 0.3684210526315789
City: Tampa, Number of addresses: 56, Number of georeferenced points: 7, ratio: 0.125
City: Virginia Beach not found
City: Washington, Number of addresses: 381, Number of georeferenced points: 56, ratio: 0.14698162729658792

### AI Model

In [7]:
# Iteració  AI OCR
ratios={}
for element in city_list:
  file_path = f'ai_files/{element}/geo_{element}.csv'
  if os.path.exists(file_path):
    geo_city = pd.read_csv(f'ai_files/{element}/geo_{element}.csv')

    geo_addresscount = geo_city['full_address'].notna().sum()
    geo_located = geo_city['Lat'].count()
    print(f"City: {element}, Number of addresses: {geo_addresscount}, Number of georeferenced points: {geo_located}, ratio: {geo_located/geo_addresscount}")
    ratios.update({element:geo_located/geo_addresscount})
  else:
      print(f"City: {element} not found")
      continue

City: Atlanta, Number of addresses: 135, Number of georeferenced points: 39, ratio: 0.28888888888888886
City: Austin, Number of addresses: 41, Number of georeferenced points: 17, ratio: 0.4146341463414634
City: Boston, Number of addresses: 589, Number of georeferenced points: 338, ratio: 0.5738539898132428
City: Charlotte, Number of addresses: 22, Number of georeferenced points: 10, ratio: 0.45454545454545453
City: Chicago, Number of addresses: 1478, Number of georeferenced points: 1070, ratio: 0.7239512855209743
City: Cincinnati, Number of addresses: 132, Number of georeferenced points: 35, ratio: 0.26515151515151514
City: Cleveland, Number of addresses: 41, Number of georeferenced points: 21, ratio: 0.5121951219512195
City: Columbus, Number of addresses: 85, Number of georeferenced points: 32, ratio: 0.3764705882352941
City: Dallas, Number of addresses: 86, Number of georeferenced points: 42, ratio: 0.4883720930232558
City: Denver, Number of addresses: 136, Number of georeferenced points: 103, ratio: 0.7573529411764706
City: Detroit, Number of addresses: 185, Number of georeferenced points: 43, ratio: 0.23243243243243245
City: Fort Lauderdale not found
City: Fort Worth, Number of addresses: 105, Number of georeferenced points: 13, ratio: 0.12380952380952381
City: Houston, Number of addresses: 157, Number of georeferenced points: 16, ratio: 0.10191082802547771
City: Indianapolis, Number of addresses: 180, Number of georeferenced points: 26, ratio: 0.14444444444444443
City: Kansas City, Number of addresses: 648, Number of georeferenced points: 129, ratio: 0.19907407407407407
City: Las Vegas not found
City: Lexington, Number of addresses: 15, Number of georeferenced points: 9, ratio: 0.6
City: Los Angeles, Number of addresses: 609, Number of georeferenced points: 156, ratio: 0.2561576354679803
City: Miami not found
City: Milwaukee, Number of addresses: 200, Number of georeferenced points: 57, ratio: 0.285
City: Minneapolis, Number of addresses: 331, Number of georeferenced points: 49, ratio: 0.14803625377643503
City: Nashville, Number of addresses: 99, Number of georeferenced points: 28, ratio: 0.2828282828282828
City: New York not found
City: Newark, Number of addresses: 186, Number of georeferenced points: 69, ratio: 0.3709677419354839
City: Orlando not found
City: Philadelphia, Number of addresses: 1141, Number of georeferenced points: 536, ratio: 0.4697633654688869
City: Phoenix, Number of addresses: 39, Number of georeferenced points: 17, ratio: 0.4358974358974359
City: Pittsburgh, Number of addresses: 414, Number of georeferenced points: 189, ratio: 0.45652173913043476
City: Portland, Number of addresses: 692, Number of georeferenced points: 229, ratio: 0.3309248554913295
City: Providence, Number of addresses: 112, Number of georeferenced points: 72, ratio: 0.6428571428571429
City: Riverside not found
City: Sacramento, Number of addresses: 77, Number of georeferenced points: 32, ratio: 0.4155844155844156
City: Saint Louis, Number of addresses: 367, Number of georeferenced points: 210, ratio: 0.5722070844686649
City: San Antonio, Number of addresses: 112, Number of georeferenced points: 33, ratio: 0.29464285714285715
City: San Diego, Number of addresses: 105, Number of georeferenced points: 12, ratio: 0.11428571428571428
City: San Francisco, Number of addresses: 357, Number of georeferenced points: 104, ratio: 0.2913165266106443
City: San Jose, Number of addresses: 21, Number of georeferenced points: 1, ratio: 0.047619047619047616
City: Seattle, Number of addresses: 449, Number of georeferenced points: 169, ratio: 0.37639198218262804
City: Tampa, Number of addresses: 60, Number of georeferenced points: 18, ratio: 0.3
City: Virginia Beach not found
City: Washington, Number of addresses: 373, Number of georeferenced points: 65, ratio: 0.1742627345844504

In [8]:
kc = pd.read_csv('ai_files/Kansas City/geo_Kansas City.csv')
kc

,Company Name or Owners's Name,City,Company type,building,address,full_address,Lat,Lon
0,Independence Inv. Co.,Kansas City,Real Estate:,NaN,222 W. Lexington,"222 W. Lexington, Kansas City, Missouri, USA",39.111368,-94.559172
1,"JNO. A, EATON",Kansas City,Attorney:,300 U. S. & Mex. Trust bldg.,NaN,"300 U. S. & Mex. Trust bldg., Kansas City, Mis...",NaN,NaN
2,S. A. AKINS & CO.,Kansas City,Real Estate:,325 Midland bldg.,NaN,"325 Midland bldg., Kansas City, Missouri, USA",NaN,NaN
3,ALLISON & RITCHIE LAND CO.,Kansas City,Land Companies:,NaN,Union Depot,"Union Depot, Kansas City, Missouri, USA",NaN,NaN
4,BAIRD & HUSELTON,Kansas City,Real Estate:,Junction bldg.,NaN,"Junction bldg., Kansas City, Missouri, USA",NaN,NaN
...,...,...,...,...,...,...,...,...
646,J. A. Wright,Kansas City,Real Estate:,Shukert bldg.,NaN,"Shukert bldg., Kansas City, Missouri, USA",NaN,NaN
647,L. R. Wright,Kansas City,Real Estate:,R. A. Long bidg.,NaN,"R. A. Long bidg., Kansas City, Missouri, USA",NaN,NaN
648,M. B Wright,Kansas City,Real Estate:,NaN,919 Baltimore ave.,"919 Baltimore ave., Kansas City, Missouri, USA",39.103268,-94.584067
649,James R. Young,Kansas City,Real Estate:,Ridge bldg.,NaN,"Ridge bldg., Kansas City, Missouri, USA",NaN,NaN
650,Zavala Land Inv. Co.,Kansas City,Real Estate:,NaN,502 Grand Ave.,"502 Grand Ave., Kansas City, Missouri, USA",38.963621,-94.588594

### Buildings and Addresses:

Comparison of the two models looking at the number of buildings and number of addresses geographically located for each type of ocr.

## Geolocated Buildings

### Tesseract

In [9]:
# TESSERACT
# Ratios of buildings not geolocated in the df
empty_buildings = {}
for element in city_list:
  file_path = f'geo_files/{element}/geo_{element}.csv'
  if os.path.exists(file_path):
    geo_city = pd.read_csv(f'geo_files/{element}/geo_{element}.csv')
    if geo_city['Building'].notnull().any():
      total_buildings = geo_city['Building'].count()
      total_geoloc = geo_city[geo_city['Building'].notnull()]['Latitude'].count()
      ratio = round((total_geoloc/total_buildings)*100,2)
      print(f"City: {element}, has {total_buildings} buildings. From those {total_geoloc} where geolocated, a ratio of {ratio}")

  else:
    print(f"City: {element} not found")
    continue

City: Atlanta, has 81 buildings. From those 9 where geolocated, a ratio of 11.11
City: Austin, has 7 buildings. From those 2 where geolocated, a ratio of 28.57
City: Boston, has 83 buildings. From those 0 where geolocated, a ratio of 0.0
City: Charlotte, has 7 buildings. From those 0 where geolocated, a ratio of 0.0
City: Chicago, has 46 buildings. From those 3 where geolocated, a ratio of 6.52
City: Cincinnati, has 57 buildings. From those 2 where geolocated, a ratio of 3.51
City: Cleveland, has 126 buildings. From those 1 where geolocated, a ratio of 0.79
City: Columbus, has 31 buildings. From those 4 where geolocated, a ratio of 12.9
City: Dallas, has 54 buildings. From those 0 where geolocated, a ratio of 0.0
City: Denver, has 54 buildings. From those 0 where geolocated, a ratio of 0.0
City: Detroit, has 23 buildings. From those 0 where geolocated, a ratio of 0.0
City: Fort Lauderdale not found
City: Fort Worth, has 24 buildings. From those 0 where geolocated, a ratio of 0.0
City: Houston, has 102 buildings. From those 2 where geolocated, a ratio of 1.96
City: Indianapolis, has 81 buildings. From those 0 where geolocated, a ratio of 0.0
City: Kansas City, has 457 buildings. From those 2 where geolocated, a ratio of 0.44
City: Las Vegas not found
City: Lexington, has 1 buildings. From those 0 where geolocated, a ratio of 0.0
City: Los Angeles, has 475 buildings. From those 22 where geolocated, a ratio of 4.63
City: Miami not found
City: Milwaukee, has 86 buildings. From those 2 where geolocated, a ratio of 2.33
City: Minneapolis, has 206 buildings. From those 4 where geolocated, a ratio of 1.94
City: Nashville, has 15 buildings. From those 0 where geolocated, a ratio of 0.0
City: New York, has 42 buildings. From those 17 where geolocated, a ratio of 40.48
City: Newark, has 5 buildings. From those 0 where geolocated, a ratio of 0.0
City: Orlando not found
City: Philadelphia, has 174 buildings. From those 2 where geolocated, a ratio of 1.15
City: Phoenix, has 3 buildings. From those 0 where geolocated, a ratio of 0.0
City: Pittsburgh, has 140 buildings. From those 32 where geolocated, a ratio of 22.86
City: Portland, has 469 buildings. From those 132 where geolocated, a ratio of 28.14
City: Providence, has 33 buildings. From those 0 where geolocated, a ratio of 0.0
City: Riverside not found
City: Sacramento, has 7 buildings. From those 0 where geolocated, a ratio of 0.0
City: Saint Louis, has 118 buildings. From those 35 where geolocated, a ratio of 29.66
City: San Antonio, has 54 buildings. From those 1 where geolocated, a ratio of 1.85
City: San Diego, has 4 buildings. From those 0 where geolocated, a ratio of 0.0
City: San Francisco, has 150 buildings. From those 37 where geolocated, a ratio of 24.67
City: San Jose, has 3 buildings. From those 1 where geolocated, a ratio of 33.33
City: Seattle, has 385 buildings. From those 139 where geolocated, a ratio of 36.1
City: Tampa, has 24 buildings. From those 0 where geolocated, a ratio of 0.0
City: Virginia Beach not found
City: Washington, has 85 buildings. From those 20 where geolocated, a ratio of 23.53

In [10]:
# AI
# Ratios of buildings not geolocated in the df
empty_buildings = {}
for element in city_list:
  file_path = f'ai_files/{element}/geo_{element}.csv'
  if os.path.exists(file_path):
    geo_city = pd.read_csv(f'ai_files/{element}/geo_{element}.csv')
    if geo_city['building'].notnull().any():
      total_buildings = geo_city['building'].count()
      total_geoloc = geo_city[geo_city['building'].notnull()]['Lat'].count()
      ratio = round((total_geoloc/total_buildings)*100,2)
      print(f"City: {element}, has {total_buildings} buildings. From those {total_geoloc} where geolocated, a ratio of {ratio}")

  else:
    print(f"City: {element} not found")
    continue

City: Atlanta, has 114 buildings. From those 30 where geolocated, a ratio of 26.32
City: Austin, has 12 buildings. From those 2 where geolocated, a ratio of 16.67
City: Boston, has 95 buildings. From those 26 where geolocated, a ratio of 27.37
City: Charlotte, has 9 buildings. From those 1 where geolocated, a ratio of 11.11
City: Chicago, has 36 buildings. From those 10 where geolocated, a ratio of 27.78
City: Cincinnati, has 83 buildings. From those 4 where geolocated, a ratio of 4.82
City: Cleveland, has 189 buildings. From those 2 where geolocated, a ratio of 1.06
City: Columbus, has 40 buildings. From those 7 where geolocated, a ratio of 17.5
City: Dallas, has 56 buildings. From those 0 where geolocated, a ratio of 0.0
City: Denver, has 207 buildings. From those 4 where geolocated, a ratio of 1.93
City: Detroit, has 238 buildings. From those 34 where geolocated, a ratio of 14.29
City: Fort Lauderdale not found
City: Fort Worth, has 49 buildings. From those 4 where geolocated, a ratio of 8.16
City: Houston, has 148 buildings. From those 12 where geolocated, a ratio of 8.11
City: Indianapolis, has 118 buildings. From those 5 where geolocated, a ratio of 4.24
City: Kansas City, has 594 buildings. From those 108 where geolocated, a ratio of 18.18
City: Las Vegas not found
City: Lexington, has 1 buildings. From those 0 where geolocated, a ratio of 0.0
City: Los Angeles, has 477 buildings. From those 89 where geolocated, a ratio of 18.66
City: Miami not found
City: Milwaukee, has 97 buildings. From those 22 where geolocated, a ratio of 22.68
City: Minneapolis, has 302 buildings. From those 31 where geolocated, a ratio of 10.26
City: Nashville, has 19 buildings. From those 0 where geolocated, a ratio of 0.0
City: New York not found
City: Newark, has 20 buildings. From those 0 where geolocated, a ratio of 0.0
City: Orlando not found
City: Philadelphia, has 295 buildings. From those 64 where geolocated, a ratio of 21.69
City: Phoenix, has 8 buildings. From those 0 where geolocated, a ratio of 0.0
City: Pittsburgh, has 157 buildings. From those 55 where geolocated, a ratio of 35.03
City: Portland, has 494 buildings. From those 156 where geolocated, a ratio of 31.58
City: Providence, has 32 buildings. From those 1 where geolocated, a ratio of 3.12
City: Riverside not found
City: Sacramento, has 18 buildings. From those 2 where geolocated, a ratio of 11.11
City: Saint Louis, has 125 buildings. From those 40 where geolocated, a ratio of 32.0
City: San Antonio, has 81 buildings. From those 8 where geolocated, a ratio of 9.88
City: San Diego, has 14 buildings. From those 0 where geolocated, a ratio of 0.0
City: San Francisco, has 138 buildings. From those 41 where geolocated, a ratio of 29.71
City: Seattle, has 383 buildings. From those 132 where geolocated, a ratio of 34.46
City: Tampa, has 40 buildings. From those 3 where geolocated, a ratio of 7.5
City: Virginia Beach not found
City: Washington, has 93 buildings. From those 22 where geolocated, a ratio of 23.66

## Table of empty buildings ratio per city

### Tesseract

In [11]:
# TESSERACT
# Table of empty buildings ratio per city
data = []
for element in city_list:
  file_path = f'geo_files/{element}/geo_{element}.csv'

  if os.path.exists(file_path):
    geo_city = pd.read_csv(f'geo_files/{element}/geo_{element}.csv')
    if geo_city['Building'].notnull().any():
      total_buildings = geo_city['Building'].count()
      total_geoloc = geo_city[geo_city['Building'].notnull()]['Latitude'].count()
      ratio = round((total_geoloc/total_buildings)*100,2)
      data.append([element, total_buildings, total_geoloc, ratio])

  else:
    print(f"City: {element} not found")
    continue
located_buildings = pd.DataFrame(data, columns=["city", "total_B", "geoloc_B", "ratio"])

located_buildings.to_csv('other/unlocated_buildings.csv', index=False)
located_buildings

City: Fort Lauderdale not found
City: Las Vegas not found
City: Miami not found
City: Orlando not found
City: Riverside not found
City: Virginia Beach not found

             city  total_B  geoloc_B  ratio
0         Atlanta       81         9  11.11
1          Austin        7         2  28.57
2          Boston       83         0   0.00
3       Charlotte        7         0   0.00
4         Chicago       46         3   6.52
5      Cincinnati       57         2   3.51
6       Cleveland      126         1   0.79
7        Columbus       31         4  12.90
8          Dallas       54         0   0.00
9          Denver       54         0   0.00
10        Detroit       23         0   0.00
11     Fort Worth       24         0   0.00
12        Houston      102         2   1.96
13   Indianapolis       81         0   0.00
14    Kansas City      457         2   0.44
15      Lexington        1         0   0.00
16    Los Angeles      475        22   4.63
17      Milwaukee       86         2   2.33
18    Minneapolis      206         4   1.94
19      Nashville       15         0   0.00
20       New York       42        17  40.48
21         Newark        5         0   0.00
22   Philadelphia      174         2   1.15
23        Phoenix        3         0   0.00
24     Pittsburgh      140        32  22.86
25       Portland      469       132  28.14
26     Providence       33         0   0.00
27     Sacramento        7         0   0.00
28    Saint Louis      118        35  29.66
29    San Antonio       54         1   1.85
30      San Diego        4         0   0.00
31  San Francisco      150        37  24.67
32       San Jose        3         1  33.33
33        Seattle      385       139  36.10
34          Tampa       24         0   0.00
35     Washington       85        20  23.53

### AI

In [12]:
data = []
for element in city_list:
  file_path = f'ai_files/{element}/geo_{element}.csv'

  if os.path.exists(file_path):
    geo_city = pd.read_csv(f'ai_files/{element}/geo_{element}.csv')
    if geo_city['building'].notnull().any():
      total_buildings = geo_city['building'].count()
      total_geoloc = geo_city[geo_city['building'].notnull()]['Lat'].count()
      ratio = round((total_geoloc/total_buildings)*100,2)
      data.append([element, total_buildings, total_geoloc, ratio])

  else:
    print(f"City: {element} not found")
    continue
located_buildings = pd.DataFrame(data, columns=["city", "total_B", "geoloc_B", "ratio"])

located_buildings.to_csv('other/AI_unlocated_buildings.csv', index=False)
located_buildings

City: Fort Lauderdale not found
City: Las Vegas not found
City: Miami not found
City: New York not found
City: Orlando not found
City: Riverside not found
City: Virginia Beach not found

             city  total_B  geoloc_B  ratio
0         Atlanta      114        30  26.32
1          Austin       12         2  16.67
2          Boston       95        26  27.37
3       Charlotte        9         1  11.11
4         Chicago       36        10  27.78
5      Cincinnati       83         4   4.82
6       Cleveland      189         2   1.06
7        Columbus       40         7  17.50
8          Dallas       56         0   0.00
9          Denver      207         4   1.93
10        Detroit      238        34  14.29
11     Fort Worth       49         4   8.16
12        Houston      148        12   8.11
13   Indianapolis      118         5   4.24
14    Kansas City      594       108  18.18
15      Lexington        1         0   0.00
16    Los Angeles      477        89  18.66
17      Milwaukee       97        22  22.68
18    Minneapolis      302        31  10.26
19      Nashville       19         0   0.00
20         Newark       20         0   0.00
21   Philadelphia      295        64  21.69
22        Phoenix        8         0   0.00
23     Pittsburgh      157        55  35.03
24       Portland      494       156  31.58
25     Providence       32         1   3.12
26     Sacramento       18         2  11.11
27    Saint Louis      125        40  32.00
28    San Antonio       81         8   9.88
29      San Diego       14         0   0.00
30  San Francisco      138        41  29.71
31        Seattle      383       132  34.46
32          Tampa       40         3   7.50
33     Washington       93        22  23.66

## Located Adresses

### Tesseract

In [13]:
# TESSERACT #
# Same for addresses
# Table of empty addresses ratio per city
data = []
for element in city_list:
  file_path = f'geo_files/{element}/geo_{element}.csv'
  if os.path.exists(file_path):
    geo_city = pd.read_csv(f'geo_files/{element}/geo_{element}.csv')
    if geo_city['Address'].notnull().any():
      total_address = geo_city['Address'].count()
      total_geoloc = geo_city[geo_city['Address'].notnull()]['Latitude'].count()
      ratio = round((total_geoloc/total_address)*100,2)
      data.append([element, total_address, total_geoloc, ratio])

  else:
    print(f"City: {element} not found")
    continue
located_addresses = pd.DataFrame(data, columns=["city", "total_A", "geoloc_A", "ratio"])
located_addresses

City: Fort Lauderdale not found
City: Las Vegas not found
City: Miami not found
City: Orlando not found
City: Riverside not found
City: Virginia Beach not found

             city  total_A  geoloc_A  ratio
0         Atlanta       43        19  44.19
1          Austin       30        11  36.67
2          Boston      558       275  49.28
3       Charlotte       16         9  56.25
4         Chicago     1697       924  54.45
5      Cincinnati       73        18  24.66
6       Cleveland      100        27  27.00
7        Columbus       35        11  31.43
8          Dallas      106        15  14.15
9          Denver      106         5   4.72
10        Detroit       26         4  15.38
11     Fort Worth       72        13  18.06
12        Houston       52        14  26.92
13   Indianapolis      119        20  16.81
14    Kansas City      280        59  21.07
15      Lexington       14         7  50.00
16    Los Angeles      273       102  37.36
17      Milwaukee      134        61  45.52
18    Minneapolis      176        25  14.20
19      Nashville       79        48  60.76
20       New York     3513      2579  73.41
21         Newark      224       125  55.80
22   Philadelphia     1348       549  40.73
23        Phoenix       30        11  36.67
24     Pittsburgh      259        93  35.91
25       Portland      208       109  52.40
26     Providence      106        79  74.53
27     Sacramento       72        34  47.22
28    Saint Louis      262       169  64.50
29    San Antonio       53        22  41.51
30      San Diego       92        12  13.04
31  San Francisco      278        54  19.42
32       San Jose       33         3   9.09
33        Seattle      147        57  38.78
34          Tampa       32         7  21.88
35     Washington      300        36  12.00

### AI

In [14]:
# AI OCR

# Same for addresses

data = []
for element in city_list:
  file_path = f'ai_files/{element}/geo_{element}.csv'
  if os.path.exists(file_path):
    geo_city = pd.read_csv(f'ai_files/{element}/geo_{element}.csv')
    if geo_city['address'].notnull().any():
      total_address = geo_city['address'].count()
      total_geoloc = geo_city[geo_city['address'].notnull()]['Lat'].count()
      ratio = round((total_geoloc/total_address)*100,2)
      data.append([element, total_address, total_geoloc, ratio])


  else:
    print(f"City: {element} not found")
    continue
located_addresses = pd.DataFrame(data, columns=["city", "total_A", "geoloc_A", "ratio"])
located_addresses.to_csv('other/AI_located_addresses.csv', index=False)
located_addresses

City: Fort Lauderdale not found
City: Las Vegas not found
City: Miami not found
City: New York not found
City: Orlando not found
City: Riverside not found
City: Virginia Beach not found

             city  total_A  geoloc_A  ratio
0         Atlanta       21         9  42.86
1          Austin       29        15  51.72
2          Boston      606       312  51.49
3       Charlotte       13         9  69.23
4         Chicago     1442      1060  73.51
5      Cincinnati       73        31  42.47
6       Cleveland      208        19   9.13
7        Columbus       45        25  55.56
8          Dallas      128        42  32.81
9          Denver      274        99  36.13
10        Detroit       82         9  10.98
11     Fort Worth       56         9  16.07
12        Houston        9         4  44.44
13   Indianapolis       62        21  33.87
14    Kansas City      248        26  10.48
15      Lexington       14         9  64.29
16    Los Angeles      284        71  25.00
17      Milwaukee      149        35  23.49
18    Minneapolis      155        23  14.84
19      Nashville       97        28  28.87
20         Newark      200        69  34.50
21   Philadelphia     1117       472  42.26
22        Phoenix       31        17  54.84
23     Pittsburgh      257       134  52.14
24       Portland      198        73  36.87
25     Providence      112        72  64.29
26     Sacramento       73        30  41.10
27    Saint Louis      245       170  69.39
28    San Antonio       31        25  80.65
29      San Diego       91        12  13.19
30  San Francisco      219        63  28.77
31       San Jose       21         1   4.76
32        Seattle       66        37  56.06
33          Tampa       36        16  44.44
34     Washington      282        43  15.25

### Unique building Names

In [15]:
# TESSERACT
# For each city find unique building names
empty_buildings = []

for city in city_list:
  count = 0
  file_path = f'geo_files/{city}/geo_{city}.csv'
  if os.path.exists(file_path):
    geo_city = pd.read_csv(f'geo_files/{city}/geo_{city}.csv')
    if geo_city['Building'].notnull().any() and geo_city['Latitude'].isna().any():
      unique_buildings = geo_city['Building'].unique()
      count = len(unique_buildings)
      year = 1912
      # print(f"City: {city}, Unique building names: {unique_buildings}")
      empty_buildings.append([city, year, unique_buildings, count])
  else:
    print(f"City: {city} not found")
    continue
empty_buildings = pd.DataFrame(empty_buildings, columns=["city","year", "unique_buildings", "count"])
empty_buildings

City: Fort Lauderdale not found
City: Las Vegas not found
City: Miami not found
City: Orlando not found
City: Riverside not found
City: Virginia Beach not found

,city,year,unique_buildings,count
0,Atlanta,1912,"[nan, 6th floor liver Trust building, 4thN. ...",41
1,Austin,1912,"[nan, McDonald building, 7 Gpenhelmer buildi...",8
2,Boston,1912,"[nan, 1030 Old So. building, J. angles 236 J...",81
3,Charlotte,1912,"[nan, 7 Wilkinson building, Trust building, ...",7
4,Chicago,1912,"[nan, 504 Chicage Sav. Bk. building, 931-7 U...",44
5,Cincinnati,1912,"[nan, 300301 Livingston building, 32 Thomas ...",51
6,Cleveland,1912,"[nan, building, 701 Park building, Engineer...",119
7,Columbus,1912,"[nan, 1201 Harrison building, Brunson buildi...",20
8,Dallas,1912,"[nan, 724 Sinughter building, 905 Practorinn...",51
9,Denver,1912,"[nan, 724 Sinughter building, 905 Practorinn...",51
10,Detroit,1912,"[nan, 1011 Majestic building, 31 Home Bank. ...",24
11,Fort Worth,1912,"[nan, 31213 F. M. Bank. building, 211 Wheat...",25
12,Houston,1912,"[nan, Bank. building, 710 Stewart building, ...",95
13,Indianapolis,1912,"[nan, Indians Trade. building, Law building,...",79
14,Kansas City,1912,"[nan, Trust building, 325 Midland building, ...",426
15,Lexington,1912,"[nan, Trade. Co. building]",2
16,Los Angeles,1912,"[nan, Title Inn. building, 80468 Trust Sav....",439
17,Milwaukee,1912,"[nan, 613 Merrill building, J. Mabbett. 30 S...",85
18,Minneapolis,1912,"[nan, 715 Enlace building, Palnce building, ...",196
19,Nashville,1912,"[nan, 7 Noel building, 300 Un. Bank. buildin...",15
20,New York,1912,"[nan, Times building, Fuller building, Marb...",16
21,Newark,1912,"[nan, 516 Essex building, 324 Prud. building...",6
22,Philadelphia,1912,"[nan, 649 Drexel building, 812 Heed building...",165
23,Phoenix,1912,"[nan, Bank building, Rma 2-3 Lewis building,...",4
24,Pittsburgh,1912,"[nan, Berger building, Oliver building, Mac...",54
25,Portland,1912,"[nan, N. CLARK. Spalding building, Corbett b...",164
26,Providence,1912,"[nan, 610Ind. Trade. building, 601 Union Tra...",34
27,Sacramento,1912,"[nan, Hartley. People's Sav. Bank. building, ...",8
28,Saint Louis,1912,"[nan, 800 Mech. Am. Bank building, ca oe 206...",70
29,San Antonio,1912,"[nan, 410 Central Office building, 305 Kampm...",55
30,San Diego,1912,"[nan, 203 Keating building, Savage. Union bu...",5
31,San Francisco,1912,"[nan, 8026 Claus Spreckles building, tat Nat...",66
32,San Jose,1912,"[nan, 7174 Auzerais building, ist Nat. Bank ...",4
33,Seattle,1912,"[nan, 601 Colman building, Colman building, ...",185
34,Tampa,1912,"[nan, . ight building, Hampson building, Gid...",20
35,Washington,1912,"[nan, Mansey building, Evans building, Cent...",48

### AI

In [16]:
# AI MODEL
# For each city find unique building names

empty_buildings = []

for city in city_list:
  count = 0
  file_path = f'ai_files/{city}/geo_{city}.csv'
  if os.path.exists(file_path):
    geo_city = pd.read_csv(f'ai_files/{city}/geo_{city}.csv')
    if geo_city['building'].notnull().any() and geo_city['Lat'].isna().any():
      unique_buildings = geo_city['building'].unique()
      count = len(unique_buildings)
      year = 1912
      # print(f"City: {city}, Unique building names: {unique_buildings}")
      empty_buildings.append([city, year, unique_buildings, count])
  else:
    print(f"City: {city} not found")
    continue
empty_buildings = pd.DataFrame(empty_buildings, columns=["city", "year", "unique_buildings", "count"])
empty_buildings

City: Fort Lauderdale not found
City: Las Vegas not found
City: Miami not found
City: New York not found
City: Orlando not found
City: Riverside not found
City: Virginia Beach not found

,city,year,unique_buildings,count
0,Atlanta,1912,"[Candler bldg., nan, Equitable bldg., Hillyer ...",52
1,Austin,1912,"[Masonic Temple, nan, Little-field bldg., McDo...",11
2,Boston,1912,"[nan, John Hancock bldg., 1030 Old So. b'dg., ...",36
3,Charlotte,1912,"[7 Wilkinson bldg., Trust bldg., Piedmont bldg...",7
4,Chicago,1912,"[Title Trust bidg., nan, 504 Chicage Sav. Bk. ...",28
5,Cincinnati,1912,"[nan, 300-301 Livingston bldg., 32 Thomas bldg...",78
6,Cleveland,1912,"[Soc. for Sav. bldg., Park bldg., nan, Enginee...",70
7,Columbus,1912,"[Wyandotte bldg., Harrison bldg., nan, Brunson...",27
8,Dallas,1912,"[724 Slaughter bldg, 810 Slaughter bldg, nan, ...",22
9,Denver,1912,"[Continental bldg., Bymes bid., E. & C. bldg.,...",79
10,Detroit,1912,"[nan, Majestic bldg., Union Trust bldg., Ford ...",163
11,Fort Worth,1912,"[First Nat. Bk. bidg., nan, F. & M. Bk. bldg.,...",33
12,Houston,1912,"[315 Com. Nat. Bank bldg., Com. Nat. Bk. bldg....",139
13,Indianapolis,1912,"[Lemcke Annex, Law Bldg., Indiana Tr. bldg., L...",46
14,Kansas City,1912,"[nan, 300 U. S. & Mex. Trust bldg., 325 Midlan...",188
15,Lexington,1912,"[nan, Tr. Co. bldg]",2
16,Los Angeles,1912,"[Title Inn. bldg., nan, Nat'l Bank bidg, Higgi...",249
17,Milwaukee,1912,"[nan, Metropolitan blk., Merrill bldg., German...",44
18,Minneapolis,1912,"[Phoenix bldg., Globe bldg., Andrus bldg., Pal...",95
19,Nashville,1912,"[23 Vanderbilt bldg., nan, 1st Nat'l Bank, bld...",18
20,Newark,1912,"[nan, Essex Bldg., Essex, Union Bldg., Prud. B...",11
21,Philadelphia,1912,"[nan, Drexel bldg., Ledger bldg., Heed bldg., ...",126
22,Phoenix,1912,"[nan, Fleming bldg., Nat. Bank bldg., Goodrich...",7
23,Pittsburgh,1912,"[Commonwealth bldg., nan, Bridge at., Century ...",53
24,Portland,1912,"[Chamber of Com. bldg., Fenton bidg., nan, Yeo...",139
25,Providence,1912,"[Case-Mead bldg., nan, Ind. Tr. bidg, Union Tr...",22
26,Sacramento,1912,"[nan, Forum bldg., Ochsner bldg., Ochaner bldg...",12
27,Saint Louis,1912,"[Homer bldg., nan, Mech. Am. Bank bldg., Chest...",64
28,San Antonio,1912,"[Washer bldg., Chamber of Commerce bldg., nan,...",47
29,San Diego,1912,"[Union Bldg., Amer. Nat. Bank bldg., nan, Hill...",11
30,San Francisco,1912,"[MacDonough bldg., nan, First National Bank bi...",58
31,Seattle,1912,"[Empire bldg., Alaska bld., Colman bk., Colman...",156
32,Tampa,1912,"[nan, Hampson bldg., Giddens bldg., 1st Nat. B...",25
33,Washington,1912,"[nan, Munsey Building, Evans bldg., Munsey bld...",58

In [17]:
# Creaning dataframe of unlocated buildings:
# each element in the unique builiding list of each city should be a single row.

empty_buildings = empty_buildings.explode('unique_buildings').reset_index(drop=True)
# removing space at beginning and leading periods

empty_buildings['unique_buildings'] = empty_buildings['unique_buildings'].str.strip().str.replace(r'^\.', '', regex=True)

# Sorting by 'city' and 'cleaned_buildings'
empty_buildings = empty_buildings.sort_values(by=['city', 'unique_buildings'])

empty_buildings
empty_buildings.to_csv('other/AI_empty_bnames.csv', index=False)

In [24]:
# Total geolocated elements
data = []
for city in city_list:
  file_path = f'ai_files/{city}/geo_{city}.csv'
  if os.path.exists(file_path):

    geo_city = pd.read_csv(f'ai_files/{city}/geo_{city}.csv')
    address = geo_city['address'].count()
    building = geo_city['building'].count()
    full_address = geo_city['full_address'].count()
    geoloc = geo_city['Lat'].count()
    total = len(geo_city)
    ratio = round((geoloc/total)*100,2)
    data.append([city, address, building, full_address, geoloc, ratio])
  else:
    print(f"City: {city} not found")
    continue

city_map = pd.DataFrame(data, columns=["city", "address", "building", "full_address", "geoloc", "ratio"])
city_map
city_map.to_csv('other/AI_city_summary.csv', index=False)

City: Fort Lauderdale not found
City: Las Vegas not found
City: Miami not found
City: New York not found
City: Orlando not found
City: Riverside not found
City: Virginia Beach not found

## List of empty addresses:

### AI

In [19]:
AI_empty_addresses = []

for city in city_list:
  count = 0
  file_path = f'ai_files/{city}/geo_{city}.csv'
  if os.path.exists(file_path):
    geo_city = pd.read_csv(f'ai_files/{city}/geo_{city}.csv')
    if geo_city['address'].notnull().any() and geo_city['Lat'].isna().any():
      unique_addresses = geo_city['address'].unique()
      count = len(unique_addresses)
      year = 1912
      AI_empty_addresses.append([city, year, unique_addresses, count])
      # print(f"City: {city}, Unique building names: {unique_buildings}")
  else:
    print(f"City: {city} not found")
    continue

AI_empty_addresses = pd.DataFrame(AI_empty_addresses, columns=["city", "year", "unique_addresses", "count"])
AI_empty_addresses
AI_empty_addresses.to_csv('other/AI_empty_addresses.csv', index=False)

City: Fort Lauderdale not found
City: Las Vegas not found
City: Miami not found
City: New York not found
City: Orlando not found
City: Riverside not found
City: Virginia Beach not found

In [20]:
data

[['Atlanta',
  np.int64(43),
  np.int64(81),
  np.int64(118),
  np.int64(28),
  np.float64(18.54)],
 ['Austin',
  np.int64(30),
  np.int64(7),
  np.int64(37),
  np.int64(13),
  np.float64(25.0)],
 ['Boston',
  np.int64(558),
  np.int64(83),
  np.int64(641),
  np.int64(275),
  np.float64(35.48)],
 ['Charlotte',
  np.int64(16),
  np.int64(7),
  np.int64(23),
  np.int64(9),
  np.float64(33.33)],
 ['Chicago',
  np.int64(1697),
  np.int64(46),
  np.int64(1743),
  np.int64(927),
  np.float64(49.87)],
 ['Cincinnati',
  np.int64(73),
  np.int64(57),
  np.int64(130),
  np.int64(20),
  np.float64(12.99)],
 ['Cleveland',
  np.int64(100),
  np.int64(126),
  np.int64(224),
  np.int64(28),
  np.float64(11.07)],
 ['Columbus',
  np.int64(35),
  np.int64(31),
  np.int64(66),
  np.int64(15),
  np.float64(14.56)],
 ['Dallas',
  np.int64(106),
  np.int64(54),
  np.int64(160),
  np.int64(15),
  np.float64(8.06)],
 ['Denver',
  np.int64(106),
  np.int64(54),
  np.int64(160),
  np.int64(5),
  np.float64(2.7)],
 ['Detroit',
  np.int64(26),
  np.int64(23),
  np.int64(45),
  np.int64(4),
  np.float64(7.41)],
 ['Fort Worth',
  np.int64(72),
  np.int64(24),
  np.int64(96),
  np.int64(13),
  np.float64(10.83)],
 ['Houston',
  np.int64(52),
  np.int64(102),
  np.int64(152),
  np.int64(16),
  np.float64(8.33)],
 ['Indianapolis',
  np.int64(119),
  np.int64(81),
  np.int64(200),
  np.int64(20),
  np.float64(9.3)],
 ['Kansas City',
  np.int64(280),
  np.int64(457),
  np.int64(735),
  np.int64(61),
  np.float64(7.15)],
 ['Lexington',
  np.int64(14),
  np.int64(1),
  np.int64(15),
  np.int64(7),
  np.float64(35.0)],
 ['Los Angeles',
  np.int64(273),
  np.int64(475),
  np.int64(744),
  np.int64(124),
  np.float64(14.69)],
 ['Milwaukee',
  np.int64(134),
  np.int64(86),
  np.int64(218),
  np.int64(63),
  np.float64(25.0)],
 ['Minneapolis',
  np.int64(176),
  np.int64(206),
  np.int64(382),
  np.int64(29),
  np.float64(6.59)],
 ['Nashville',
  np.int64(79),
  np.int64(15),
  np.int64(94),
  np.int64(48),
  np.float64(45.28)],
 ['New York',
  np.int64(3513),
  np.int64(42),
  np.int64(3555),
  np.int64(2596),
  np.float64(70.91)],
 ['Newark',
  np.int64(224),
  np.int64(5),
  np.int64(229),
  np.int64(125),
  np.float64(52.52)],
 ['Philadelphia',
  np.int64(1348),
  np.int64(174),
  np.int64(1522),
  np.int64(551),
  np.float64(33.19)],
 ['Phoenix',
  np.int64(30),
  np.int64(3),
  np.int64(33),
  np.int64(11),
  np.float64(20.0)],
 ['Pittsburgh',
  np.int64(259),
  np.int64(140),
  np.int64(399),
  np.int64(125),
  np.float64(26.6)],
 ['Portland',
  np.int64(208),
  np.int64(469),
  np.int64(677),
  np.int64(241),
  np.float64(29.07)],
 ['Providence',
  np.int64(106),
  np.int64(33),
  np.int64(139),
  np.int64(79),
  np.float64(53.02)],
 ['Sacramento',
  np.int64(72),
  np.int64(7),
  np.int64(79),
  np.int64(34),
  np.float64(36.96)],
 ['Saint Louis',
  np.int64(262),
  np.int64(118),
  np.int64(380),
  np.int64(204),
  np.float64(43.5)],
 ['San Antonio',
  np.int64(53),
  np.int64(54),
  np.int64(107),
  np.int64(23),
  np.float64(16.79)],
 ['San Diego',
  np.int64(92),
  np.int64(4),
  np.int64(96),
  np.int64(12),
  np.float64(10.62)],
 ['San Francisco',
  np.int64(278),
  np.int64(150),
  np.int64(428),
  np.int64(91),
  np.float64(18.69)],
 ['San Jose',
  np.int64(33),
  np.int64(3),
  np.int64(36),
  np.int64(4),
  np.float64(9.52)],
 ['Seattle',
  np.int64(147),
  np.int64(385),
  np.int64(532),
  np.int64(196),
  np.float64(26.56)],
 ['Tampa',
  np.int64(32),
  np.int64(24),
  np.int64(56),
  np.int64(7),
  np.float64(9.72)],
 ['Washington',
  np.int64(300),
  np.int64(85),
  np.int64(381),
  np.int64(56),
  np.float64(13.46)]]

In [21]:
empty_b = pd.read_csv(f"other/AIempty_bnames.csv")

In [22]:
empty_b

            city          unique_buildings  count
0        Atlanta             10 Auburn av.     52
1        Atlanta                106½ Whall     52
2        Atlanta            12 Auburn ave.     52
3        Atlanta               13 N. Pryor     52
4        Atlanta            14 Auburn ave.     52
...          ...                       ...    ...
2174  Washington      Wash. Loan & T. bldg     58
2175  Washington     Wash. Loan & T. bldg.     58
2176  Washington    Wash. Loan & Tr. bldg.     58
2177  Washington  Wash. Loan & Trust bldg.     58
2178  Washington                       NaN     58

[2179 rows x 3 columns]